imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: ../../vendor/knplabs/doctrine-behaviors/config/orm-services.yml }
    - { resource: services.yml }


framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'sonata_form_fields.html.twig'
        - 'kalamu_form_fields.html.twig'
        - 'SonataCoreBundle:Form:datepicker.html.twig'

sonata_core:
    form:
        mapping:
            enabled: false

sonata_admin:
    title:      Kalamu
    title_logo: bundles/kalamucmsadmin/image/logo_32X32.png
    templates:
        user_block: AppBundle:Administration:user_block.html.twig
    dashboard:
        blocks:
            - { position: top, class: col-md-12, type: kalamu.sonata_block.dashboard }
    security:
        handler: sonata.admin.security.handler.role
    extensions:
        kalamu_cms.admin_extension.contextualizable:
            instanceof:
                - Kalamu\CmsCoreBundle\ContentType\Interfaces\ContextualizableInterface

sonata_block:
    default_contexts: [cms]
    blocks:

        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.number_stats: ~
        sonata.block.service.chart_stats: ~
        kalamu.sonata_block.dashboard: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

kalamu_cms_core:
    menus:
        header_menu_default: Main menu
    enable_contexts: false
    default_context_inclusive: false
#    contexts:
#        private_space:
#            title: Private space
#            prefix: /private-space
#        public:
#            title: Public
#            prefix: /
    types:
        -
            name: page
            label: Pages
            entity: KalamuCmsAdminBundle:Page
            identifier: slug
            has_index: false
            template: AppBundle:Site:page.html.twig
#            templates:
#                standard:
#                    title: Standard
#                    template: AppBundle:Site:page.html.twig
#                private_space:
#                    title: Private space
#                    template: AppBundle:Site:page_private_space.html.twig
#            contexts:
#                private_space: []
#                public: []
        -
            name: post
            label: Posts
            entity: KalamuCmsAdminBundle:Post
            identifier: slug
            has_index: true
            template: AppBundle:Post:post.html.twig
            template_index: AppBundle:Post:index.html.twig
            max_per_page: 5
#            contexts:
#                private_space: []
#                public: []
        -
            name: term
            label: Terms
            entity: KalamuCmsAdminBundle:Term
            template: AppBundle:Term:term.html.twig
            controller_read: AppBundle:Term:read
            has_index: false
            default_menu_item_picker: true
            stringifier: libelle
            identifier: slug
            has_rss: false

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Kalamu\CmsAdminBundle\Entity\User
    from_email:
        address: 'webmaster@%main_domain%'
        sender_name: "Webmaster - %main_domain%"



fm_elfinder:
    instances:
        img_cms:
            locale: %locale% # defaults to current request locale
            editor: form # other options are tinymce, tinymce4, fm_tinymce,  form, simple, custom
            #editor_template: set custom template for your editor # default null
            #path_prefix: /
            #fullscreen: true|false # defaults true, applies to simple and ckeditor editors
            #theme: smoothness # jquery theme, default is 'smoothness'
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            #visible_mime_types: ['image/png', 'image/jpg', 'image/jpeg'] # only show these mime types, defaults to show all
            connector:
                #debug: true|false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        #show_hidden: true|false # defaults to false, hide files that
                        driver: LocalFileSystem
                        path: uploads/img
                        upload_allow: ['image']
                        upload_deny: ['all']
                        upload_max_size: 2M
                        #attributes: example of setting attributes permission
                        #    - { pattern: '/(.*?)/', read: true, write: false, locked: true }
        docs_cms:
            locale: %locale% # defaults to current request locale
            editor: form
            include_assets: true
            connector:
                roots:       # at least one root must be defined
                    uploads:
                        #show_hidden: true|false # defaults to false, hide files that
                        driver: LocalFileSystem
                        path: uploads/
                        upload_allow: ['all']
                        upload_max_size: 2M
                        #attributes: example of setting attributes permission
                        #    - { pattern: '/(.*?)/', read: true, write: false, locked: true }

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~

        post_thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [300, 190], mode: inbound }
        post_fullsize:
            quality: 75
            filters:
                thumbnail: { size: [1000, 400], mode: inbound }
        medium_thumb:
            quality: 75
            filters:
                thumbnail: { size: [240, 160], mode: inbound }
        slider_home:
            quality: 75
            filters:
                thumbnail: { size: [1900, 500], mode: inbound }


kalamu_dashboard:
    contexts:
        cms:
            types:
                cms.content:
                    standard:
                        - kalamu_cms.element.cms.wysiwyg
                    media:
                        - kalamu_cms.element.cms.image
                        - kalamu_cms.element.cms.youtube
                    other:
                        - kalamu_cms.element.cms.menu
                        - kalamu_cms.element.cms.google_map
                        - kalamu_cms.element.cms.form_contact
                cms.section:
                    standard:
                        - kalamu_cms.element.cms.section_standard
        user_dashboard:
            types:
                cms.infos:
                    default:
                        - kalamu_cms.element.cms.last_content

kalamu_menu_service:
    main_admin:
        items:
            -
                label: Go to the website
                route: cms_homepage
                icon: '<i class="fa fa-fw fa-home"></i>'
            - {label: "Pages", route: admin_kalamu_cmsadmin_page_list, icon: '<i class="fa fa-fw fa-file"></i>', roles: [ROLE_KALAMU_CMS_ADMIN_PAGE_LIST] }
            - {label: "Posts", route: admin_kalamu_cmsadmin_post_list, icon: '<i class="fa fa-fw fa-file"></i>', roles: [ROLE_KALAMU_CMS_ADMIN_ADMIN_POST_LIST] }
            - {label: "Menu", route: admin_kalamu_cmsadmin_menu_list, icon: '<i class="fa fa-fw fa-list"></i>', roles: [ROLE_KALAMU_CMS_ADMIN_ADMIN_MENU_LIST] }
            -
                label: Users
                route: ''
                icon: '<i class="fa fa-fw fa-users"></i>'
                hide_if_no_child: true
                items:
                    - {label: "Users", route: admin_kalamu_cmsadmin_user_list, icon: '<i class="fa fa-fw fa-user"></i>', roles: [ROLE_KALAMU_CMS_ADMIN_USER_LIST] }
                    - {label: "Groups", route: admin_kalamu_cmsadmin_group_list, icon: '<i class="fa fa-fw fa-users"></i>', roles: [ROLE_KALAMU_CMS_ADMIN_GROUP_LIST] }
            -
                label: "Configuration"
                route: ''
                icon: '<i class="fa fa-fw fa-gears"></i>'
                hide_if_no_child: true
                items:
                    - {label: "Website configuration", route: dynamique_configurator, icon: '<i class="fa fa-fw fa-folder"></i>', roles: [ROLE_ADMIN_CONFIGURATION] }
                    - {label: "Publish status", route: admin_kalamu_cmsadmin_publishstatus_list, icon: '<i class="fa fa-fw fa-folder"></i>', roles: [ROLE_KALAMU_CMS_ADMIN_ADMIN_PUBLISH_STATUS_LIST] }
                    - {label: "Terms", route: admin_kalamu_cmsadmin_term_list, icon: '<i class="fa fa-fw fa-folder"></i>', roles: [ROLE_KALAMU_CMS_ADMIN_ADMIN_TERM_LIST] }
                    - {label: "Taxonomies", route: admin_kalamu_cmsadmin_taxonomy_list, icon: '<i class="fa fa-fw fa-folder"></i>', roles: [ROLE_KALAMU_CMS_ADMIN_ADMIN_TAXONOMY_LIST] }

