services:

    # Security voter to give full access to the super admin
    kalamu.security.voter.super_admin:
        class: AppBundle\Voter\SuperAdminVoter
        public: false
        tags:
            - { name: security.voter }


